version: "3.7"

services:
  db2:
    image: postgres
    hostname: db2
    container_name: db2
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rinha123
      POSTGRES_DB: rinha2
    volumes:
      - ./config/script.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d rinha2"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: '1.4GB'
    network_mode: "host"
  
  rinha2:
    # image: rinha:0.9.0
    image: go-rt-dev:1.21
    volumes:
      - ./src:/app
    container_name: rinha2
    hostname: rinha2
    expose:
      - "9999"
    # ports:
    #   - "9999:9999"
    # env_file: .env.docker
    environment:
      - GOGC=1000
      - GOMAXPROCS=2
      - WEB_SERVER_PORT=9999
    depends_on:
      db2:
        condition: service_healthy
        restart: true
    restart: on-failure:6
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '1.3GB'
    network_mode: "host"  
  
